### ISSUE TITLE
Elevators

### ISSUE THREAD

**Issue by charles-hall** [talloakdesign/ahuntsic360#7]
Need 360 in each major elevator:
- A
- B
- C
- G

Also get a 360 in T stairwell, on a curve.

I'll do similar to Vanier with edited floor icons in each elevator to navigate.

**Comment by thekipper** [comment]
Should this be shot with door open or door closed? @talloakdesign

**Comment by charles-hall** [comment]
@thekipper doors closed, so it's not floor specific

**Comment by charles-hall** [comment]
Will be available in Beta 1.
